# Site settings
title: 'Blog' # Your Title
tagline: 'Stuff that comes to my mind' # A brief tagline for your site
sidebar_image: /images/blog_cover.png

# Build settings
markdown: redcarpet
highlighter: pygments
baseurl: /blog # the subpath of your site, e.g. /blog/
