# Site settings
title: "Rudra's blog" # Your Title
tagline: 'Stuff that comes to my mind' # A brief tagline for your site
sidebar_image: /images/blog_cover.png

# Build settings
markdown: redcarpet
highlighter: pygments
baseurl: /blog_v2 # the subpath of your site, e.g. /blog/
